version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: product-db

    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: mysecretkeymysecretkeymysecretkeymysecretkey
      SPRING_JPA_SHOW_SQL: false
      LOGGING_LEVEL_ORG_HIBERNATE: ERROR
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: OFF
      LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND: OFF

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: product-api

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/product_management
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: mysecretkeymysecretkeymysecretkeymysecretkey

volumes:
  postgres_data: