spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: postgres
    password: postgres

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true