spring.application.name=product-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
secret: ${JWT_SECRET}

# Disable Hibernate SQL logs
spring.jpa.show-sql=false

# Reduce Hibernate logging
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# Reduce Spring JPA logs
logging.level.org.springframework.orm.jpa=ERROR
logging.level.org.springframework.transaction=ERROR

# Keep application logs clean
logging.level.root=INFO